### ISSUE TITLE
Alt text

### ISSUE THREAD

**Issue by dphiffer** [MLTSHP/best-of-mltshp-bot#1]
Currently Mastodon is using a preview card that offers no alt text. The oEmbed spec, used to construct the preview card, does not offer a way to describe photo types with accessible descriptions. It could be possible to patch Mastodon/Hometown to support a non-standard oEmbed properties. Alternatively we could download, then upload, each media file and include alt text in the uploaded media.

**Comment by macmanx2** [comment]
> we could download, then upload, each media file and include alt text in the uploaded media.

That would be kinder to the MLTSHP servers too, since we wouldn't have to worry about every individual Mastodon instance fetching and caching the link preview.

**Comment by dphiffer** [comment]
Yeah, I think you're right. I hadn't considered the server load aspect of preview cards, that makes sense. I've gone ahead and implemented the download/upload feature. Let's see if it works!

**Comment by dphiffer** [comment]
I also started setting up a Hometown dev environment, but that will likely be a longer running process.

**Comment by dphiffer** [comment]
This is fixed!
